// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniClass.Data;

#nullable disable

namespace UniClass.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230711080731_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniClass.Models.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d34ba28-9a0d-4e02-8f17-04c3c31a3d5c"),
                            Name = "Business Information Systems"
                        },
                        new
                        {
                            Id = new Guid("4912c961-39d9-4ba1-b035-523e700280c0"),
                            Name = "Business Management"
                        },
                        new
                        {
                            Id = new Guid("33977982-bbe3-44ed-89e4-00cad7e6f6ed"),
                            Name = "Commercial Law"
                        });
                });

            modelBuilder.Entity("UniClass.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Funding")
                        .HasColumnType("int");

                    b.Property<Guid?>("MajorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd0907e7-8362-4397-b198-b302a53274f4"),
                            DateOfBirth = new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "Malika Temurova",
                            Funding = 0,
                            MajorId = new Guid("9d34ba28-9a0d-4e02-8f17-04c3c31a3d5c")
                        },
                        new
                        {
                            Id = new Guid("5b8d9c60-e4d9-4cc5-81c6-085846d2d8a5"),
                            DateOfBirth = new DateTime(1979, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mavluda Asalxodjaeva",
                            Funding = 1,
                            MajorId = new Guid("4912c961-39d9-4ba1-b035-523e700280c0")
                        },
                        new
                        {
                            Id = new Guid("5c5e59cb-aa76-4a24-a1d6-0ff904d0cfb9"),
                            DateOfBirth = new DateTime(1980, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Munisa Rizaeva",
                            Funding = 1,
                            MajorId = new Guid("4912c961-39d9-4ba1-b035-523e700280c0")
                        },
                        new
                        {
                            Id = new Guid("ca2089a7-327b-44c7-9d2a-edcbe3049991"),
                            DateOfBirth = new DateTime(1981, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sitora Tulyaganova",
                            Funding = 2,
                            MajorId = new Guid("33977982-bbe3-44ed-89e4-00cad7e6f6ed")
                        });
                });

            modelBuilder.Entity("UniClass.Models.Student", b =>
                {
                    b.HasOne("UniClass.Models.Major", "Major")
                        .WithMany("Students")
                        .HasForeignKey("MajorId");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("UniClass.Models.Major", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
